version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'react'
        versions:
          - '8.3.0'
      - dependency-name: 'react-dom'
        versions:
          - '8.3.0'
