name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
jobs:
  test:
    runs-on: self-hosted
    env:
      SEISMIC_ROOT: /home/azureuser/seismic/seismic
      RETH_DATA_DIR: /home/azureuser/.seismic-reth/data
      RETH_STATIC_FILES: /home/azureuser/.seismic-reth/static_files
      SEISMIC_RETH_FILES: /home/azureuser/.seismic-reth
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build reth
        run: |
          cd "$SEISMIC_ROOT"
          cargo build --release --bin reth
      - name: Return to main repo
        run: cd "$GITHUB_WORKSPACE"
      - name: Create .env
        run: |
          echo "SEISMIC_ROOT=$SEISMIC_ROOT" > .env
          echo "RETH_DATA_DIR=$RETH_DATA_DIR" >> .env
          echo "RETH_STATIC_FILES=$RETH_STATIC_FILES" >> .env
      - name: Install dependencies
        run: bun install
      - name: Test devnet
        run: bun viem:test:devnet
      - name: Remove reth files
        run: rm -rf "$SEISMIC_RETH_FILES"
      - name: Test anvil
        run: bun viem:test:anvil
