name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42
      - name: Install dependencies
        run: bun install
      - name: Check lint
        run: bun run lint:check

  typecheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42
      - name: Install dependencies
        run: bun install
      - name: Check typing
        run: bun run typecheck

  test:
    runs-on: self-hosted
    concurrency:
      group: global-self-hosted-runner
      cancel-in-progress: false
    env:
      SRETH_ROOT: /home/azureuser/seismic/seismic-reth
      SFOUNDRY_ROOT: /home/azureuser/seismic/seismic-foundry
      RETH_DATA_DIR: /home/azureuser/.seismic-reth/data
      RETH_STATIC_FILES: /home/azureuser/.seismic-reth/static_files
      SEISMIC_RETH_FILES: /home/azureuser/.seismic-reth
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Build reth
        run: |
          cd "$SRETH_ROOT"
          cargo build --bin seismic-reth
      - name: Return to main repo
        run: cd "$GITHUB_WORKSPACE"
      - name: Create .env
        run: |
          echo "SRETH_ROOT=$SRETH_ROOT" > .env
          echo "RETH_DATA_DIR=$RETH_DATA_DIR" >> .env
          echo "RETH_STATIC_FILES=$RETH_STATIC_FILES" >> .env
      - name: Install dependencies
        run: bun install
      - name: Test devnet
        run: bun viem:test:devnet
      - name: Remove reth files
        run: rm -rf "$SEISMIC_RETH_FILES"
      - name: Test anvil
        run: bun viem:test:anvil
